const mongoose = require("mongoose");

const ApartmentSchema = new mongoose.Schema({
  name: String,
  firstImage: String,
  images: Array,
  rooms: Number,
  beds: Number,
  price: Number,
  area: String,
  city: String,
  phone: String,
  short: String,
  long: String,
  mail: String,
  priceMethod: String,
  special: Array,
});

const Apartment = mongoose.model("Apartments", ApartmentSchema);

const product1 = new Apartment({
  name: "הצימר של אירית",
  firstImage:
    "https://zarfati-zvi.com/wp-content/uploads/2014/12/gallery_12.jpg",
  images: [
    "https://zarfati-zvi.com/wp-content/uploads/2014/12/gallery_12.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],
  rooms: 8,
  beds: 10,
  price: 100,
  area: "צפון",
  city: "מירון",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "מיטה",
  special: [
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product2 = new Apartment({
  name: "סייסטה ברמות",
  firstImage:
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
  images: [
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 7,
  beds: 15,
  price: 600,
  area: "צפון",
  city: "קרית שמונה",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "זוג",
  special: [
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product3 = new Apartment({
  name: "נקודת חן",
  firstImage:
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
  images: [
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 2,
  beds: 8,
  price: 400,
  area: "דרום",
  city: "תפרח",
  phone: "058-4112424",
  mail: "yosef9987@walla.com",
  priceMethod: "דירה",
  special: [
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product4 = new Apartment({
  name: "אחוזת גלית בצפת",
  firstImage:
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
  images: [
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 9,
  beds: 56,
  price: 90,
  area: "דרום",
  city: "אופקים",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "אדם",
  special: [
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product5 = new Apartment({
  name: "בקתות התפוח",
  firstImage: "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
  images: [
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 4,
  beds: 22,
  price: 850,
  area: "מרכז",
  city: "פתח תקוה",
  phone: "058-4112424",
  mail: "yosef9987@walla.com",
  priceMethod: "לילה",
  special: [
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product6 = new Apartment({
  name: "צימרים אחוזת דבש",
  firstImage: "https://dira4u.co.il/storage/2020/10/1-2.jpeg",

  images: [
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 7,
  beds: 17,
  price: 120,
  area: "מרכז",
  city: "ראשון לציון",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "מיטה",
  special: [
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product7 = new Apartment({
  name: "חלומות ספיר",
  firstImage:
    "https://metaylimbkipa.com/wp-content/uploads/thumbs/74d66485-b335-4cde-8244-f52b89c6d6ae-3b4923mlhc4e0ata0r12ww.jpg",
  images: [
    "https://metaylimbkipa.com/wp-content/uploads/thumbs/74d66485-b335-4cde-8244-f52b89c6d6ae-3b4923mlhc4e0ata0r12ww.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 18,
  beds: 50,
  price: 23650,
  area: "ירושלים",
  city: "ביתר",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "אדם",
  special: [
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "מטבחון",
    "מכונת אספרסו",
    "פינת קפה ותה",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product8 = new Apartment({
  name: "אחוזת רוטצי",
  firstImage: "https://uploads.homeless.co.il/sale/202006/nvFile3861212.jpg",
  images: [
    "https://uploads.homeless.co.il/sale/202006/nvFile3861212.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 6,
  beds: 4,
  price: 2000,
  area: "ירושלים",
  city: "תל ציון",
  phone: "058-4112424",
  mail: "yosef9987@walla.com",
  priceMethod: "לילה",
  special: [
    "פינות ישיבה בחצר",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product9 = new Apartment({
  name: "טוסקנה בשזור",
  firstImage: "https://img2.ad.co.il/NadlanSaleImages/1102789_0.jpg",
  images: [
    "https://img2.ad.co.il/NadlanSaleImages/1102789_0.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],
  rooms: 8,
  beds: 10,
  price: 1000,
  area: "צפון",
  city: "צפת",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "דירה",
  special: [
    "פינות ישיבה בחצר",
    "מזגן",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product10 = new Apartment({
  name: "סוויטות כחול לבן",
  firstImage:
    "https://images1.ynet.co.il/PicServer5/2017/02/15/7590673/75897210100791980551no.jpg",
  images: [
    "https://images1.ynet.co.il/PicServer5/2017/02/15/7590673/75897210100791980551no.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 7,
  beds: 15,
  price: 60,
  area: "צפון",
  city: "יבניאל",
  phone: "058-4112424",
  mail: "yosef9987@walla.com",
  priceMethod: "מיטה",
  special: [
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product11 = new Apartment({
  name: "בקתות לוטן",
  firstImage:
    "https://www.israelhayom.co.il/sites/default/files/styles/566x349/public/images/articles/2020/07/10/15943294905962_b.jpg",
  images: [
    "https://www.israelhayom.co.il/sites/default/files/styles/566x349/public/images/articles/2020/07/10/15943294905962_b.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 2,
  beds: 8,
  price: 400,
  area: "דרום",
  city: "נתיבות",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "לזוג",
  special: [
    "פינות ישיבה בחצר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product12 = new Apartment({
  name: "צימר האפרסק",
  firstImage:
    "https://ainevo.co.il/wp-content/uploads/elementor/thumbs/dira1_c-Medium-1024x728-ogie6jc9med5opsjdt3wp20l2tftccacq9otq5pymg.jpg",

  images: [
    "https://ainevo.co.il/wp-content/uploads/elementor/thumbs/dira1_c-Medium-1024x728-ogie6jc9med5opsjdt3wp20l2tftccacq9otq5pymg.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 9,
  beds: 56,
  price: 90,
  area: "דרום",
  city: "באר שבע",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "אדם",
  special: [
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product13 = new Apartment({
  name: "קסם האלה",
  firstImage: "https://images1.ynet.co.il/PicServer5/2017/08/21/7983208/3.jpg",
  images: [
    "https://images1.ynet.co.il/PicServer5/2017/08/21/7983208/3.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 4,
  beds: 22,
  price: 850,
  area: "מרכז",
  city: "בני ברק",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "דירה",
  special: [
    "פינות ישיבה בחצר",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product14 = new Apartment({
  name: "בקתות נוף הצוק",
  firstImage:
    "https://www.ahouse.co.il/upload/imgs/db7fe1017d08492307d7d70d458fe488.jpg",
  images: [
    "https://www.ahouse.co.il/upload/imgs/db7fe1017d08492307d7d70d458fe488.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 7,
  beds: 17,
  price: 1260,
  area: "מרכז",
  city: "תל אביב",
  phone: "058-4112424",
  mail: "yosef9987@walla.com",
  priceMethod: "לילה",
  special: [
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product15 = new Apartment({
  name: "אחוזת ארגמן",
  firstImage: "https://img3.ad.co.il/NadlanSaleImages/1614750_0.jpg",
  images: [
    "https://img3.ad.co.il/NadlanSaleImages/1614750_0.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],
  rooms: 18,
  beds: 250,
  price: 50,
  area: "ירושלים",
  city: "ירושלים",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "אדם",
  special: [
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product16 = new Apartment({
  name: "בתי נורית",
  firstImage:
    "https://refamily.co.il/wp-content/uploads/2020/07/%D7%94%D7%A8%D7%95%D7%A4%D7%90-41-%D7%9E%D7%98%D7%91%D7%97.jpg",
  images: [
    "https://refamily.co.il/wp-content/uploads/2020/07/%D7%94%D7%A8%D7%95%D7%A4%D7%90-41-%D7%9E%D7%98%D7%91%D7%97.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],
  rooms: 6,
  beds: 4,
  price: 200,
  area: "ירושלים",
  city: "בית שמש",
  phone: "058-4112424",
  mail: "yosef9987@walla.com",
  priceMethod: "מיטה",
  special: [
    "פינות ישיבה בחצר",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});
const product17 = new Apartment({
  name: "אחוזה בגליל",
  firstImage:
    "http://www.yokra-estate.co.il/images/com_jea/images/489/GARDEN.jpg",
  images: [
    "http://www.yokra-estate.co.il/images/com_jea/images/489/GARDEN.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],
  rooms: 8,
  beds: 10,
  price: 1000,
  area: "צפון",
  city: "מירון",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "זוג",
  special: [
    "פינות ישיבה בחצר",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product18 = new Apartment({
  name: "אחוזת שרונה",
  firstImage:
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
  images: [
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 7,
  beds: 15,
  price: 600,
  area: "צפון",
  city: "קרית שמונה",
  phone: "058-4112424",
  mail: "yosef9987@walla.com",
  priceMethod: "לילה",
  special: [
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product19 = new Apartment({
  name: "בוסתן בכפר",
  firstImage:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb9Om3Uu5NytnjOeUnTTlD793pPeqcPkAS3A&usqp=CAU",
  images: [
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb9Om3Uu5NytnjOeUnTTlD793pPeqcPkAS3A&usqp=CAU",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],
  rooms: 2,
  beds: 8,
  price: 400,
  area: "דרום",
  city: "תפרח",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "זוג",
  special: [
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product20 = new Apartment({
  name: "הפינה הקסומה במושב",
  firstImage:
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
  images: [
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 9,
  beds: 56,
  price: 90,
  area: "דרום",
  city: "אופקים",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "מיטה",
  special: [
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product21 = new Apartment({
  name: "סוויטות אמיליה",
  firstImage:
    "https://img.mako.co.il/2018/10/16/Appartment_In_Tel_Aviv_0918_Zion_13_i.jpg",
  images: [
    "https://img.mako.co.il/2018/10/16/Appartment_In_Tel_Aviv_0918_Zion_13_i.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],
  rooms: 4,
  beds: 22,
  price: 850,
  area: "מרכז",
  city: "פתח תקוה",
  phone: "058-4112424",
  mail: "yosef9987@walla.com",
  priceMethod: "דירה",
  special: [
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product22 = new Apartment({
  name: "צליל בגליל",
  firstImage:
    "https://uploads.homeless.co.il/shortterm/201206/300/nvFile3777377.jpeg",
  images: [
    "https://uploads.homeless.co.il/shortterm/201206/300/nvFile3777377.jpeg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],

  rooms: 7,
  beds: 17,
  price: 1260,
  area: "מרכז",
  city: "ראשון לציון",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "לילה",
  special: [
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product23 = new Apartment({
  name: "אחוזת אורפז",
  firstImage:
    "https://www.halel.co.il/wp-content/uploads/2018/02/DSC2480AAA_copy.jpg",
  images: [
    "https://www.halel.co.il/wp-content/uploads/2018/02/DSC2480AAA_copy.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],
  rooms: 18,
  beds: 250,
  price: 23650,
  area: "ירושלים",
  city: "ביתר",
  phone: "058-4112424",
  mail: "yosef9987@gmail.com",
  priceMethod: "זוג",
  special: [
    "פינות ישיבה בחצר",
    "מזגן",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "ערסל",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "בית כנסת קרוב",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

const product24 = new Apartment({
  name: "אחוזת פאר בדלתון",
  firstImage: "https://img.mako.co.il/2018/12/26/6_Rooms_Money_261218_22_i.jpg",
  images: [
    "https://img.mako.co.il/2018/12/26/6_Rooms_Money_261218_22_i.jpg",
    "https://www.halel.co.il/wp-content/uploads/2018/06/DSC2016AAA_copy.jpg",
    "https://www.nadlancoda.co.il/wp-content/uploads/2021/08/3V8A3198-26.jpg",
    "https://zimuki.com/wp-content/uploads/2019/02/Jerusalem.of_.gold_.3br.apt0003.jpg",
    "https://dira4u.co.il/storage/2020/10/1-2.jpeg",
    "https://pics.yad2.co.il/Pics/2018/03/20180321164933.jpg",
    "https://images1.calcalist.co.il/PicServer3/2018/07/22/834349/3L.jpg",
  ],
  rooms: 6,
  beds: 4,
  price: 2000,
  area: "ירושלים",
  city: "תל ציון",
  phone: "058-4112424",
  mail: "yosef9987@walla.com",
  priceMethod: "לילה",
  special: [
    "פינות ישיבה בחצר",
    "מזגן",
    "נוף",
    "חצר",
    "מקום לברביקיו",
    "אינטרנט אלחוטי",
    "פינת קפה ותה",
    "קומקום חשמלי",
    "מקרר",
    "מיקרוגל",
    "כיריים חשמליות",
    "נדנדה",
    "מנגל",
    "חנייה פרטית",
    "ריהוט גן",
    "פינת ישיבה מול הנוף",
    "פלטת שבת",
    "מיחם לשבת",
    "בית כנסת קרוב",
    "ג'קוזי",
    "מטבחון",
    "מכונת אספרסו",
    "מינימרקט",
    "בריכה פרטית",
    "ארוחת בוקר",
    "מגבות",
    "ערסל",
  ],
  short: "דירה יפהפיה, צמוד לבית כנסת, מרחבי דשא.",
  long: "קוטג' חדש נקי ומטופח + סלון מטבח. חצר מאובזרת עם נדנדות וטרמפולינה. נוף מדהים פתוח, ללא היזק ראיה. גינת משחקים ובית כנסת צמודים. במרחק הליכה מפארק ענק. מקום אידיאלי לשבתות משפחתיות.",
});

// product1.save();
// product2.save();
// product3.save();
// product4.save();
// product5.save();
// product6.save();
// product7.save();
// product8.save();
// product9.save();
// product10.save();
// product11.save();
// product12.save();
// product13.save();
// product14.save();
// product15.save();
// product16.save();
// product17.save();
// product18.save();
// product19.save();
// product20.save();
// product21.save();
// product22.save();
// product23.save();
// product24.save();

module.exports = Apartment;
